### ISSUE TITLE
Missing support for ProjectTo

### ISSUE THREAD

**Issue by mc0re** [huysentruitw/entity-framework-core-mock#11]
The following code:
```csharp
var res = await mContext.Entities
    .ProjectTo<Model>(mMapper.ConfigurationProvider)
    .ToListAsync();
```
produces an error when executed with mocked db:
```
at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, IEnumerable`1 parameters)
   at EntityFrameworkCoreMock.DbAsyncEnumerable`1.CompileExpression[T](Expression expression)
   at EntityFrameworkCoreMock.DbAsyncEnumerable`1..ctor(Expression expression)
   at EntityFrameworkCoreMock.DbAsyncQueryProvider`1.CreateQuery(Expression expression)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand) in C:\projects\automapper\src\AutoMapper\QueryableExtensions\ProjectionExpression.cs:line 62
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand) in C:\projects\automapper\src\AutoMapper\QueryableExtensions\Extensions.cs:line 76
   at MyCode.IRepository.GetAll()
   at MyTest.RepositoryShould.Add()
Result Message:	
Test method MyTest.RepositoryShould.Add threw exception: 
System.ArgumentException: Expression of type 'System.Linq.IQueryable`1[Model]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[Entity]'
```

`ProjectTo` is `AutoMapper` extension.
Preprequisites: `Entity` class, `Model` class, and a map from `Entity` to `Model`.

**Comment by huysentruitw** [comment]
Seems like the `ProjectTo` expression expects an `IEnumerable<Entity>` where it gets a `IQueryable<Model>`. Currently, we don't tend to support extensions from 3rd party libraries, because of time constraints. If you could help and create a PR for this, I would be happy to review and add it into the library.

**Comment by mc0re** [comment]
I don't even know where to start in your code ☹️

On Mar 27, 2019 11:00, huysentruitw <notifications@github.com> wrote:

Seems like the ProjectTo expression expects an IEnumerable<Entity> where it gets a IQueryable<Model>. Currently, we don't tend to support extensions from 3rd party libraries, because of time constraints. If you could help and create a PR for this, I would be happy to review and add it into the library.

**Comment by huysentruitw** [comment]
Can you add your unit-test or create a unit-test for this project that demonstrates the problem?

**Comment by mc0re** [comment]
Hi,

I have created a test case, but I can’t create a branch to push it to, so I don’t know how to create a pull request.

Mikhail

________________________________

**Comment by huysentruitw** [comment]
Hi Mikhail,

that's correct. You'll have to create your own fork of this repository and push your changes to your own fork.

To create a fork, go here: https://github.com/huysentruitw/entity-framework-core-mock and click the Fork button. After that, you can check out your fork and commit your branch to the fork.

When you're happy with the changes, you can create a pull-request from your branch to the master branch in this repository. If that doesn't work, just point me to your branch.

Regards,
Wouter

**Comment by mc0re** [comment]
Okay, done 😊
The test case obviously fails.


________________________________

**Comment by huysentruitw** [comment]
Finally had some time to fix this. Please retry with version 1.0.0.24+. Feel free to reopen if you're still having trouble.

**Comment by mc0re** [comment]
This version requires .NET 2.2, it'll take some time before I switch the solution to that.

**Comment by huysentruitw** [comment]
You probably mean the version of EntityFramework ? Ok if I downgrade to 2.1.8?

**Comment by huysentruitw** [comment]
If so, please try version 1.0.0.25 or higher, where I've downgraded the EF Core dependency.

**Comment by mc0re** [comment]
Thanks, will do after Easter.
